services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile 
      target: development
    container_name: chatbackend
    restart: always
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/chatbackend?schema=public
      JWTSECRET: lkdsjfllfjj29u40927497yq2hundhjofds98807458fdshg4875802efgdxgfg846d49v84dsg676

    working_dir: /app
    volumes:
      - .:/app
    command: yarn run dev
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    depends_on:
      - postgres

  # postgres definitions
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chatbackend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - chatbackend:/var/lib/postgresql/data

volumes:
  chatbackend: