version: '3.4'

services:
  demochatapp:
    image: demochatapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
